import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/lib/auth";
import { Nav } from "@/components/Nav";

export const metadata: Metadata = {
  title: "Visual Algos — AI algorithm videos",
  description:
    "Type a computer-science topic and get a 3Blue1Brown-style Manim video, generated by AI.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-sans">
        <AuthProvider>
          <div className="min-h-screen flex flex-col">
            <Nav />
            <main className="flex-1">{children}</main>
            <footer className="border-t border-edge/60 py-6 text-center text-xs text-white/40">
              Visual Algos · Manim + Gemini + Firebase
            </footer>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
